### ISSUE TITLE
Selenide and Appium throwing Caused by: UnsupportedCommandException: Method is not implemented on click() method call

### ISSUE THREAD

**Issue by myrianv** [selenide/selenide-appium#64] opened 2021-12-30 19:08 UTC
## Description

I'm using SauceLabs iOS simulators. Right after test start I'm getting 405 repond with following error: Method is not implemented

## Environment

* Java 17.0.1
* Appium 1.21.0/1.22/1.20
* iOS 15/14.5:
* simulator
* Selenide 5.25.1

## Details

I was trying different versions of Java such as 16, different versions of iOS on simulators such as 14.5 and different versions of Appium server on SauceLabs such as 1.22.0, 1.20.0 and 1.20.1

## Code To Reproduce Issue [ Good To Have ]

public void clickOnGetStarted() {
        $x("//XCUIElementTypeButton[@name=\"Let's get started\"]").click();
    }

## Exception Stacktraces

https://gist.github.com/myrianv/81d38b49172f0c636efbd16d59ff3a9e

## Link To Appium Logs

https://gist.github.com/myrianv/b5e3d80bfc742386fc41aa7ca72cf6c2

**Comment by BorisOsipov** [comment] 2021-12-30 19:15
Hi @myrianv 

What is your selenide-appium version? could you check on latest v1.7.4?

**Comment by myrianv** [comment] 2021-12-30 19:28
Hello @BorisOsipov 

I'm tried to check it on selenide-appium v1.7.4 and issue is reproduced.
Looks like problem in RemoteWebDriver. Since I moved from selenide-appium and started to use IOSDriver problems dissapeared.

**Comment by asolntsev** [comment] 2022-01-01 09:47
@myrianv Do you have a sample project or something similar? How could we reproduce the problem?
How exactly did you add `selenide-appium` dependency?
I also think we already fixed it in `selenide-appium 1.7.2`

**Comment by myrianv** [comment] 2022-01-04 15:50
@asolntsev here is an import example: https://gist.github.com/myrianv/a0f55dfd571e60386eb8cea88901d5e7
Cannot share an entire project.

**Comment by asolntsev** [comment] 2022-06-27 17:01
@myrianv Still, how can we reproduce the problem? If we cannot reproduce it, we cannot fix it. 
If you cannot share en entire project, we can sign NDA and solve your problems as a normal consultancy. 

P.S. Still, I think the problem should be fixed in the latest version `com.codeborne:selenide-appium:2.0.4`

**Closed by asolntsev** 2022-06-27 17:01 UTC
